config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("school.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("school/", include("school.school_system.urls", namespace="school_system"), name="school_system"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

school/school_system/urls.py
from django.urls import path

from school.school_system.views import (
    AbsenceCreateView,
    AbsenceDeleteView,
    AbsenceDetailView,
    AbsenceListView,
    AbsenceUpdateView,
    AssignmentCreateView,
    AssignmentDeleteView,
    AssignmentDetailView,
    AssignmentListView,
    AssignmentUpdateView,
    ExcuseCreateView,
    ExcuseDeleteView,
    ExcuseDetailView,
    ExcuseListView,
    ExcuseUpdateView,
    ForumCreateView,
    ForumDeleteView,
    ForumDetailView,
    ForumListView,
    ForumPostCreateView,
    ForumPostDeleteView,
    ForumPostDetailView,
    ForumPostListView,
    ForumPostUpdateView,
    ForumUpdateView,
    GradeCreateView,
    GradeDeleteView,
    GradeDetailView,
    GradeListView,
    GradeUpdateView,
    StudentCreateView,
    StudentDeleteView,
    StudentDetailView,
    StudentListView,
    StudentUpdateView,
    TardyCreateView,
    TardyDeleteView,
    TardyDetailView,
    TardyListView,
    TardyUpdateView,
)

app_name = "school_system"

urlpatterns = [
    path("students/", StudentListView.as_view(), name="student-list"),
    path("students/<int:pk>/", StudentDetailView.as_view(), name="student-detail"),
    path("students/create/", StudentCreateView.as_view(), name="student-create"),
    path("students/<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("students/<int:pk>/delete/", StudentDeleteView.as_view(), name="student-delete"),
    # Absence URLs
    path("absences/", AbsenceListView.as_view(), name="absence-list"),
    path("absences/<int:pk>/", AbsenceDetailView.as_view(), name="absence-detail"),
    path("absences/create/", AbsenceCreateView.as_view(), name="absence-create"),
    path("absences/<int:pk>/update/", AbsenceUpdateView.as_view(), name="absence-update"),
    path("absences/<int:pk>/delete/", AbsenceDeleteView.as_view(), name="absence-delete"),
    # Tardy URLs
    path("tardies/", TardyListView.as_view(), name="tardy-list"),
    path("tardies/<int:pk>/", TardyDetailView.as_view(), name="tardy-detail"),
    path("tardies/create/", TardyCreateView.as_view(), name="tardy-create"),
    path("tardies/<int:pk>/update/", TardyUpdateView.as_view(), name="tardy-update"),
    path("tardies/<int:pk>/delete/", TardyDeleteView.as_view(), name="tardy-delete"),
    # Excuse URLs
    path("excuses/", ExcuseListView.as_view(), name="excuse-list"),
    path("excuses/<int:pk>/", ExcuseDetailView.as_view(), name="excuse-detail"),
    path("excuses/create/", ExcuseCreateView.as_view(), name="excuse-create"),
    path("excuses/<int:pk>/update/", ExcuseUpdateView.as_view(), name="excuse-update"),
    path("excuses/<int:pk>/delete/", ExcuseDeleteView.as_view(), name="excuse-delete"),
    # Assignment URLs
    path("assignments/", AssignmentListView.as_view(), name="assignment-list"),
    path("assignments/<int:pk>/", AssignmentDetailView.as_view(), name="assignment-detail"),
    path("assignments/create/", AssignmentCreateView.as_view(), name="assignment-create"),
    path("assignments/<int:pk>/update/", AssignmentUpdateView.as_view(), name="assignment-update"),
    path("assignments/<int:pk>/delete/", AssignmentDeleteView.as_view(), name="assignment-delete"),
    # Grade URLs
    path("grades/", GradeListView.as_view(), name="grade-list"),
    path("grades/<int:pk>/", GradeDetailView.as_view(), name="grade-detail"),
    path("grades/create/", GradeCreateView.as_view(), name="grade-create"),
    path("grades/<int:pk>/update/", GradeUpdateView.as_view(), name="grade-update"),
    path("grades/<int:pk>/delete/", GradeDeleteView.as_view(), name="grade-delete"),
    # Forum URLs
    path("forums/", ForumListView.as_view(), name="forum-list"),
    path("forums/<int:pk>/", ForumDetailView.as_view(), name="forum-detail"),
    path("forums/create/", ForumCreateView.as_view(), name="forum-create"),
    path("forums/<int:pk>/update/", ForumUpdateView.as_view(), name="forum-update"),
    path("forums/<int:pk>/delete/", ForumDeleteView.as_view(), name="forum-delete"),
    # ForumPost URLs
    path("forum-posts/", ForumPostListView.as_view(), name="forum-post-list"),
    path("forum-posts/<int:pk>/", ForumPostDetailView.as_view(), name="forum-post-detail"),
    path("forum-posts/create/", ForumPostCreateView.as_view(), name="forum-post-create"),
    path("forum-posts/<int:pk>/update/", ForumPostUpdateView.as_view(), name="forum-post-update"),
    path("forum-posts/<int:pk>/delete/", ForumPostDeleteView.as_view(), name="forum-post-delete"),
]

school/users/urls.py
from django.urls import path

from school.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

school/school_system/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from school.school_system.forms import (
    AbsenceForm,
    AssignmentForm,
    ExcuseForm,
    FacultyForm,
    ForumForm,
    ForumPostForm,
    GradeForm,
    StaffForm,
    StudentForm,
    TardyForm,
)
from school.school_system.models import (
    Absence,
    Assignment,
    Excuse,
    Faculty,
    Forum,
    ForumPost,
    Grade,
    Staff,
    Student,
    Tardy,
)

# Student Views


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = "students"
    template_name = "student_list.html"


class StudentDetailView(DetailView):
    model = Student
    template_name = "student_detail.html"


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    template_name = "student_form.html"
    success_url = reverse_lazy("school_system:student-list")


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = "student_form.html"
    success_url = reverse_lazy("school_system:student-list")


class StudentDeleteView(DeleteView):
    model = Student
    template_name = "student_confirm_delete.html"
    success_url = reverse_lazy("student-list")


# Faculty Views


class FacultyListView(ListView):
    model = Faculty
    template_name = "faculty_list.html"


class FacultyDetailView(DetailView):
    model = Faculty
    template_name = "faculty_detail.html"


class FacultyCreateView(CreateView):
    model = Faculty
    form_class = FacultyForm
    template_name = "faculty_form.html"
    success_url = reverse_lazy("faculty-list")


class FacultyUpdateView(UpdateView):
    model = Faculty
    form_class = FacultyForm
    template_name = "faculty_form.html"
    success_url = reverse_lazy("faculty-list")


class FacultyDeleteView(DeleteView):
    model = Faculty
    template_name = "faculty_confirm_delete.html"
    success_url = reverse_lazy("faculty-list")


# Staff Views


class StaffListView(ListView):
    model = Staff
    template_name = "staff_list.html"


class StaffDetailView(DetailView):
    model = Staff
    template_name = "staff_detail.html"


class StaffCreateView(CreateView):
    model = Staff
    form_class = StaffForm
    template_name = "staff_form.html"
    success_url = reverse_lazy("staff-list")


class StaffUpdateView(UpdateView):
    model = Staff
    form_class = StaffForm
    template_name = "staff_form.html"
    success_url = reverse_lazy("staff-list")


class StaffDeleteView(DeleteView):
    model = Staff
    template_name = "staff_confirm_delete.html"
    success_url = reverse_lazy("staff-list")


# Absence Views


class AbsenceListView(ListView):
    model = Absence
    template_name = "absence_list.html"


class AbsenceDetailView(DetailView):
    model = Absence
    template_name = "absence_detail.html"


class AbsenceCreateView(CreateView):
    model = Absence
    form_class = AbsenceForm
    template_name = "absence_form.html"
    success_url = reverse_lazy("absence-list")


class AbsenceUpdateView(UpdateView):
    model = Absence
    form_class = AbsenceForm
    template_name = "absence_form.html"
    success_url = reverse_lazy("absence-list")


class AbsenceDeleteView(DeleteView):
    model = Absence
    template_name = "absence_confirm_delete.html"
    success_url = reverse_lazy("absence-list")


# Tardy Views


class TardyListView(ListView):
    model = Tardy
    template_name = "tardy_list.html"


class TardyDetailView(DetailView):
    model = Tardy
    template_name = "tardy_detail.html"


class TardyCreateView(CreateView):
    model = Tardy
    form_class = TardyForm
    template_name = "tardy_form.html"
    success_url = reverse_lazy("tardy-list")


class TardyUpdateView(UpdateView):
    model = Tardy
    form_class = TardyForm
    template_name = "tardy_form.html"
    success_url = reverse_lazy("tardy-list")


class TardyDeleteView(DeleteView):
    model = Tardy
    template_name = "tardy_confirm_delete.html"
    success_url = reverse_lazy("tardy-list")


# Excuse Views


class ExcuseListView(ListView):
    model = Excuse
    template_name = "excuse_list.html"


class ExcuseDetailView(DetailView):
    model = Excuse
    template_name = "excuse_detail.html"


class ExcuseCreateView(CreateView):
    model = Excuse
    form_class = ExcuseForm
    template_name = "excuse_form.html"
    success_url = reverse_lazy("excuse-list")


class ExcuseUpdateView(UpdateView):
    model = Excuse
    form_class = ExcuseForm
    template_name = "excuse_form.html"
    success_url = reverse_lazy("excuse-list")


class ExcuseDeleteView(DeleteView):
    model = Excuse
    template_name = "excuse_confirm_delete.html"
    success_url = reverse_lazy("excuse-list")


# Assignment Views


class AssignmentListView(ListView):
    model = Assignment
    template_name = "assignment_list.html"


class AssignmentDetailView(DetailView):
    model = Assignment
    template_name = "assignment_detail.html"


class AssignmentCreateView(CreateView):
    model = Assignment
    form_class = AssignmentForm
    template_name = "assignment_form.html"
    success_url = reverse_lazy("assignment-list")


class AssignmentUpdateView(UpdateView):
    model = Assignment
    form_class = AssignmentForm
    template_name = "assignment_form.html"
    success_url = reverse_lazy("assignment-list")


class AssignmentDeleteView(DeleteView):
    model = Assignment
    template_name = "assignment_confirm_delete.html"
    success_url = reverse_lazy("assignment-list")


# Grade Views


class GradeListView(ListView):
    model = Grade
    template_name = "grade_list.html"


class GradeDetailView(DetailView):
    model = Grade
    template_name = "grade_detail.html"


class GradeCreateView(CreateView):
    model = Grade
    form_class = GradeForm
    template_name = "grade_form.html"
    success_url = reverse_lazy("grade-list")


class GradeUpdateView(UpdateView):
    model = Grade
    form_class = GradeForm
    template_name = "grade_form.html"
    success_url = reverse_lazy("grade-list")


class GradeDeleteView(DeleteView):
    model = Grade
    template_name = "grade_confirm_delete.html"
    success_url = reverse_lazy("grade-list")


# Forum Views


class ForumListView(ListView):
    model = Forum
    template_name = "forum_list.html"


class ForumDetailView(DetailView):
    model = Forum
    template_name = "forum_detail.html"


class ForumCreateView(CreateView):
    model = Forum
    form_class = ForumForm
    template_name = "forum_form.html"
    success_url = reverse_lazy("forum-list")


class ForumUpdateView(UpdateView):
    model = Forum
    form_class = ForumForm
    template_name = "forum_form.html"
    success_url = reverse_lazy("forum-list")


class ForumDeleteView(DeleteView):
    model = Forum
    template_name = "forum_confirm_delete.html"
    success_url = reverse_lazy("forum-list")


# ForumPost Views


class ForumPostListView(ListView):
    model = ForumPost
    template_name = "forumpost_list.html"


class ForumPostDetailView(DetailView):
    model = ForumPost
    template_name = "forumpost_detail.html"


class ForumPostCreateView(CreateView):
    model = ForumPost
    form_class = ForumPostForm
    template_name = "forumpost_form.html"
    success_url = reverse_lazy("forumpost-list")


class ForumPostUpdateView(UpdateView):
    model = ForumPost
    form_class = ForumPostForm
    template_name = "forumpost_form.html"
    success_url = reverse_lazy("forumpost-list")


class ForumPostDeleteView(DeleteView):
    model = ForumPost
    template_name = "forumpost_confirm_delete.html"
    success_url = reverse_lazy("forumpost-list")

school/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

school/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Listo paaa")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

school/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

school/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        School Management System
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="School management system " />
    <meta name="author" content="TodoViernes" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      <link href="{% static 'css/project.min.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Vendor dependencies bundled as one file -->
      <script defer src="{% static 'js/vendors.min.js' %}"></script>
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.min.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">School Management System</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div>
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>

school/templates/student_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <h2>Create Student</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock content %}

school/templates/student_list.html
{% extends "base.html" %}

{% block title %}
  Student List
{% endblock title %}
{% block content %}
  <h1>Student List</h1>
  <a href="{% url 'school_system:student-create' %}">Add New Student</a>
  <table>
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Enrollment Date</th>
        <th>Parent</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for student in object_list %}
        <tr>
          <td>{{ student.first_name }}</td>
          <td>{{ student.last_name }}</td>
          <td>{{ student.enrollment_date }}</td>
          <td>{{ student.parent.name }}</td>
          <td>
            <a href="{% url 'school_system:student-update' pk=student.pk %}">Edit</a> |
            <a href="{% url 'school_system:student-delete' pk=student.pk %}">Delete</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No students found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}